### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by lizhuoyi** [Goshin/Remove-PDF-Watermark#1]
Hello! when I open this project why i can not compile correctly?

**Comment by lizhuoyi** [comment]
can you give your wechat number,i can contact you

**Comment by Goshin** [comment]
This is a python script. Compiling is not needed.

Please provide more details about your problem.

**Comment by lizhuoyi** [comment]
what parameters should i wirte?
![1](https://user-images.githubusercontent.com/8819683/38302802-8dd71c80-3836-11e8-8910-8959cb974252.png)

**Comment by lizhuoyi** [comment]
![12](https://user-images.githubusercontent.com/8819683/38303060-7a370518-3837-11e8-82e3-a66fc9d90126.jpg)
Can you remove the watermark from the PDF file with your program?

**Comment by Goshin** [comment]
Please refer to README.

In your case, the parameter is `--output=o.pdf p.pdf`.

**Comment by Goshin** [comment]
> ![](https://user-images.githubusercontent.com/8819683/38303060-7a370518-3837-11e8-82e3-a66fc9d90126.jpg)
> Can you remove the watermark from the PDF file with your program?

Nope, this script is only intended for scanned materials with colorful watermarks.

**Comment by lizhuoyi** [comment]
Can you solve this problem?

**Comment by Goshin** [comment]
Sorry, it NOT a problem.
