### ISSUE TITLE
can't read pdf 

### ISSUE THREAD

**Issue by fanshao** [Goshin/Remove-PDF-Watermark#6]
I use python 3.6.12  on mac os 10.15.6
I run the script get this error 
    raise ValueError("not enough image data")
ValueError: not enough image data
[testDecember.pdf](https://github.com/Goshin/Remove-PDF-Watermark/files/5205766/testDecember.pdf)

**Comment by fanshao** [comment]
if I use the before.png, 
I got this error,

PyPDF2.utils.PdfReadError: EOF marker not found

**Comment by Goshin** [comment]
The script can only process scanned PDF files.
